### ISSUE TITLE
cgo argument has Go pointer to Go pointer (go 1.6)

### ISSUE THREAD

**Issue by fasterthanlime** [kothar/brotli-go#31]
With

```
$ go version
go version go1.6rc2 windows/amd64
```

...running tests fail:

```
=== RUN   TestStreamDecompression
--- FAIL: TestStreamDecompression (0.05s)
panic: runtime error: cgo argument has Go pointer to Go pointer [recovered]
        panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 5 [running]:
testing.tRunner.func1(0xc082076000)
        C:/Go/src/testing/testing.go:467 +0x199
gopkg.in/kothar/brotli-go.v0/dec.NewBrotliReaderSize(0xb8a6b0, 0xc082007f80, 0x20000, 0xb8a6b0)
        C:/msys64/home/amwenger/Dev/go/src/gopkg.in/kothar/brotli-go.v0/dec/decode.go:208 +0x130
gopkg.in/kothar/brotli-go.v0/dec.NewBrotliReader(0xb8a6b0, 0xc082007f80, 0x758ff0)
        C:/msys64/home/amwenger/Dev/go/src/gopkg.in/kothar/brotli-go.v0/dec/decode.go:195 +0x3b
gopkg.in/kothar/brotli-go.v0/dec.TestStreamDecompression(0xc082076000)
        C:/msys64/home/amwenger/Dev/go/src/gopkg.in/kothar/brotli-go.v0/dec/decode_test.go:28 +0x3c5
testing.tRunner(0xc082076000, 0x6ba5c0)
        C:/Go/src/testing/testing.go:473 +0x9f
created by testing.RunTests
        C:/Go/src/testing/testing.go:582 +0x899
FAIL    gopkg.in/kothar/brotli-go.v0/dec        0.140s
```

I'm starting to think that we should wrap the brotli interface into something sane, ie. something that returns number of bytes consumed, etc. rather than moving around a bunch of pointers.

**Comment by kothar** [comment]
Sorry, meant to push that to a branch first, but test pass with go1.6 for me - thoughts?

**Comment by fasterthanlime** [comment]
Seems to work fine, thanks for the fix! :stars:
